### PR TITLE
[Feature #11] Adding offline flag support

### PR DESCRIPTION
**Pull request by jtemplet**
Deleted the old PR, started fresh. Thank you for your help. Let me know if you have any questions or concerns.

Jason

### CODE REVIEW

**Comment by jtemplet** [comment]
@finnp @klaemo Does the PR look ok? 

I think I was able to clean it up like you suggested. LMK if there is something I can do, answer any questions, etc.

**Comment by finnp** [comment]
@jtemplet Sorry for letting you wait so long. This PR looks pretty good. There's only one issue: Since the git remote add origin happens after the `git init`, it will not add the remote to the package.json. Otherwise this looks good.

**Comment by finnp** [comment]
@jtemplet I just fixed this. So it's working now. I still want to fix the create-project issue before publishing it as 3.0.0

**Comment by jtemplet** [comment]
@finnp I [created a new module] (https://github.com/jtemplet/gitonup) as [we discussed a while back here] (https://github.com/finnp/create-module/issues/11#issuecomment-113571930)
Let me know if this is in line with what you had in mind.

Cheers

**Comment by jtemplet** [comment]
@finnp After thinking about it more, I hope I didn't misunderstand your intentions. 

Did you mean for it to be a separate module in a different repo? Or in the same repo?

**Comment by finnp** [comment]
@jtemplet Nope, that looks pretty much how I imagined it to be! Congrats to your first module :balloon:

**Pull request merged**
