### PR TITLE
[Feature #9] Added cli private flag

### PR DESCRIPTION
**Pull request by jtemplet**
As per Feature request, here it is.

### CODE REVIEW

**Comment by finnp** [comment]
Thanks for the PR!

I just thought that `--private` might be a bit of a confusing name, because there are also private npm modules and this has nothing to do with it. Maybe call it differently like `--skip-check` or `--force`?

Also I think we should add this to the error message like `If you want to create it any way run again with --skip-check`.

**Comment by jtemplet** [comment]
I understand how the private flag could be misleading or confusing. 

Maybe by default the tool should not check to see if the module name exists in npm. Maybe there should be a flag to enable 'check if the name exists in npm'. I can't speak for everyone but adding a module to npm would be an afterthought, IMO.

**Comment by finnp** [comment]
For me it's kinda important, because I normally write OS modules. However I feel like usually I already know beforehand if a module name is taken or not.

So I am fine with `--check` as an option for checking if the name is available on npm. 

@klaemo What do you think? You implemented that part :)

**Comment by klaemo** [comment]
Yep, let's go with `--check`. :)
Also, this should *technically* be a major version, because this could be considered breaking. But oh well... ;)

**Comment by finnp** [comment]
@klaemo That's what I thought :smile: Maybe we can see if we break anything else in the next couple of days with adding offline support. Then we can make it 2.0.0 for sure :wink:

**Comment by jtemplet** [comment]
Withdrawing Pull Request.

**Pull request closed without merging**
